/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  BaseContract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "ethers";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import { TypedEventFilter, TypedEvent, TypedListener } from "./commons";

interface CInterface extends ethers.utils.Interface {
  functions: {
    "numOpsA()": FunctionFragment;
    "numOpsB1()": FunctionFragment;
    "numOpsB2()": FunctionFragment;
    "runA()": FunctionFragment;
    "runAll()": FunctionFragment;
    "runB1()": FunctionFragment;
    "runB2()": FunctionFragment;
  };

  encodeFunctionData(functionFragment: "numOpsA", values?: undefined): string;
  encodeFunctionData(functionFragment: "numOpsB1", values?: undefined): string;
  encodeFunctionData(functionFragment: "numOpsB2", values?: undefined): string;
  encodeFunctionData(functionFragment: "runA", values?: undefined): string;
  encodeFunctionData(functionFragment: "runAll", values?: undefined): string;
  encodeFunctionData(functionFragment: "runB1", values?: undefined): string;
  encodeFunctionData(functionFragment: "runB2", values?: undefined): string;

  decodeFunctionResult(functionFragment: "numOpsA", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "numOpsB1", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "numOpsB2", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "runA", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "runAll", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "runB1", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "runB2", data: BytesLike): Result;

  events: {};
}

export class C extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>;
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): this;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>;

  interface: CInterface;

  functions: {
    numOpsA(overrides?: CallOverrides): Promise<[BigNumber]>;

    numOpsB1(overrides?: CallOverrides): Promise<[BigNumber]>;

    numOpsB2(overrides?: CallOverrides): Promise<[BigNumber]>;

    runA(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    runAll(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    runB1(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    runB2(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;
  };

  numOpsA(overrides?: CallOverrides): Promise<BigNumber>;

  numOpsB1(overrides?: CallOverrides): Promise<BigNumber>;

  numOpsB2(overrides?: CallOverrides): Promise<BigNumber>;

  runA(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  runAll(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  runB1(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  runB2(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    numOpsA(overrides?: CallOverrides): Promise<BigNumber>;

    numOpsB1(overrides?: CallOverrides): Promise<BigNumber>;

    numOpsB2(overrides?: CallOverrides): Promise<BigNumber>;

    runA(overrides?: CallOverrides): Promise<void>;

    runAll(overrides?: CallOverrides): Promise<void>;

    runB1(overrides?: CallOverrides): Promise<void>;

    runB2(overrides?: CallOverrides): Promise<void>;
  };

  filters: {};

  estimateGas: {
    numOpsA(overrides?: CallOverrides): Promise<BigNumber>;

    numOpsB1(overrides?: CallOverrides): Promise<BigNumber>;

    numOpsB2(overrides?: CallOverrides): Promise<BigNumber>;

    runA(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    runAll(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    runB1(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    runB2(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    numOpsA(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    numOpsB1(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    numOpsB2(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    runA(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    runAll(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    runB1(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    runB2(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;
  };
}
